# Generated by Django 4.0.5 on 2022-06-17 23:00

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=2200)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('image', stdimage.models.StdImageField(force_min_size=False, upload_to='postImages/', variations={})),
                ('likes', models.IntegerField()),
                ('reposts', models.IntegerField()),
                ('is_reposted', models.BooleanField()),
            ],
        ),
    ]
