# Generated by Django 4.0.5 on 2022-09-24 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_date'),
        ('profiles', '0004_alter_profile_following_alter_profile_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='posts',
        ),
        migrations.AddField(
            model_name='profile',
            name='posts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts_made', to='posts.post'),
        ),
    ]
